### ISSUE TITLE
building tabor on top of linkml schema using Inheritance

### ISSUE THREAD

**Issue by capsulecorplab** [geoCML/tabor#1]
It may be of interest to [validate data against a schema](https://linkml.io/linkml/data/validating-data.html#data-validation), as well as being able to [convert between representations](https://linkml.io/linkml/data/conversion.html#converting-between-different-representations) of either the schema or data. In which case, it may be useful to build tabor elements on top of linkml using [inheritance](https://linkml.io/linkml/intro/tutorial07.html#inheritance), as opposed to building the entire data model and toolchain from scratch.

**Comment by TristanDamron** [comment]
I'm definitely open to this! I've been concerned that we'll run into some limitations here, but the more I read about LinkML the more those concerns wane.

**Comment by TristanDamron** [comment]
Do you have some time this weekend/early next week to brainstorm a spec document around this?

**Comment by capsulecorplab** [comment]
This weekend is a bit booked, but can possibly do Tuesday or Wednesday evening.
